---
title: "About"
lang: en
---

## Biography

Jiihn Ahn is a PhD student in New Testament. As a Korean international student, Jiihn also spent significant time in New Orleans, LA, where he calls it second home. Diverse social dynamics in New Orleans caused him to ask questions about social class and ethnicity, and how personal background affects people’s belief about the Bible. He holds degrees from New Orleans Baptist Theological Seminary(BA), Korean Baptist Theological Univ. Seminary(MDiv) and Vanderbilt University(MTS). His interests include postcolonial biblical criticism, reception history, and racial-ethnic studies focusing on Pauline Epistles and Acts of the Apostles. Jiihn is also an ordained minister in the Korean Baptist tradition.


## Research interests

- Postcolonial Biblical Criticism and Racial-ethnic Studies
- Reception History
- Pauline Epistles and Acts of the Apostles

## Education

- **PhD in New Testament** (in progress) — Princeton Theological Seminary, 2025–present
- **MTS** — Vanderbilt University Divinity School, 2025
- **MDiv** — Korea Baptist Theological University Seminary, 2021
- **BA** — New Orleans Baptist Theological Seminary, 2015
